name: Main CI/CD

on:
  push:
    branches:
      - main

env:
  CI: 'true'

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Restore Node Modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache Node Modules
        id: cache-npm-save
        if: steps.cache-npm.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Restore Node Modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache Node Modules
        id: cache-npm-save
        if: steps.cache-npm.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Test
        run: npm run test -- --coverage

  build:
    name: Build
    runs-on: self-hosted
    needs: ['lint', 'test']
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: docker build -t bmswens/meshtak:${{ github.sha }} .

      - name: Docker Login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u bmswens -p $DOCKER_TOKEN

      - name: Docker push
        run: docker push bmswens/meshtak:${{ github.sha }}